import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
async function api(path:string,options?:RequestInit){const r=await fetch(path,options);const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Request failed');return d;}
const fmt=(v:number=0)=>v.toLocaleString(undefined,{maximumFractionDigits:2});
function App(){
 const [s,S]=useState<any>(null),[g,G]=useState<any>(null),[u,U]=useState<any[]>([]),[r,R]=useState<any>(null);
 const [busy,B]=useState(false),[message,M]=useState('Upload CSV or Excel. Existing order IDs update existing orders.');
 const [start,A]=useState(''),[end,E]=useState(''),[q,Q]=useState(''),[segment,T]=useState('All'),[page,P]=useState(1),[dark,D]=useState(false),[chart,C]=useState('bar');
 async function refresh(){const [a,b,c]=await Promise.all([api('/api/summary'),api('/api/segments'),api('/api/uploads')]);S(a);G(b);U(c);A('');E('');}
 useEffect(()=>{refresh().catch(e=>M(e.message));},[]);
 async function upload(file?:File){if(!file)return;B(true);try{const body=new FormData();body.append('file',file);const d=await api('/api/upload',{method:'POST',body});R(null);await refresh();M('Import complete: '+d.added+' added / '+d.updated+' updated / '+d.unchanged+' unchanged. Results use all stored orders.');}catch(e:any){M(e.message);}finally{B(false);}}
 async function filter(e:React.FormEvent){e.preventDefault();B(true);try{const p=new URLSearchParams();if(start)p.set('start',start);if(end)p.set('end',end);S(await api('/api/summary?'+p));M('Revenue metrics filtered. Segments and models use all data.');}catch(e:any){M(e.message);}finally{B(false);}}
 async function compare(){B(true);M('Comparing models…');try{R(await api('/api/compare-models',{method:'POST'}));M('Comparison complete.');}catch(e:any){M(e.message);}finally{B(false);}}
 const customers=(g?.customers??[]).filter((c:any)=>c.customer_id.toLowerCase().includes(q.toLowerCase())&&(segment==='All'||c.segment===segment)).sort((a:any,b:any)=>b.monetary-a.monetary);
 const months=s?.monthly??[],max=Math.max(1,...months.map((m:any)=>m.revenue));
 const counts=Object.entries(g?.counts??{}),total=counts.reduce((a,[,n])=>a+Number(n),0),colors=['#5965ed','#22a88a','#ed9460'];
 let cursor=0;const stops=counts.map(([,n],i)=>{const from=cursor;cursor+=total?Number(n)/total*100:0;return colors[i]+' '+from+'% '+cursor+'%';});
 function exportCSV(){const rows=[['customer_id','recency_days','frequency','monetary','segment'],...customers.map((c:any)=>[c.customer_id,c.recency_days,c.frequency,c.monetary,c.segment])];const text=rows.map(row=>row.map((v:any)=>'"'+String(v).split('"').join('""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='customer-segments.csv';a.click();URL.revokeObjectURL(url);}
 return <div className={dark?'app dark':'app'}><main><header><div><small>PORTFOLIO · BUSINESS ANALYTICS</small><h1>Sales Intelligence</h1><p>Explore revenue, customer behavior and model performance.</p></div><button onClick={()=>D(!dark)}>{dark?'Light':'Dark'} theme</button></header>
 <section className="panel toolbar"><label className="button">{busy?'Working…':'Upload CSV / Excel'}<input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/></label><button disabled={busy} onClick={()=>refresh().catch(e=>M(e.message))}>Refresh all data</button><p role="status" aria-live="polite">{message}</p></section>
 <form className="panel toolbar" onSubmit={filter}><label>From <input type="date" value={start} onChange={e=>A(e.target.value)}/></label><label>To <input type="date" value={end} onChange={e=>E(e.target.value)}/></label><button disabled={busy}>Apply revenue filter</button><small>Amounts use the dataset's currency.</small></form>
 <section className="cards">{[['Revenue',s?.revenue],['Orders',s?.orders],['Customers',s?.customers],['Average order',s?.average_order]].map(([k,v])=><div key={k}><small>{k}</small><strong>{fmt(v)}</strong></div>)}</section>
 <section className="grid"><div className="panel"><div className="heading"><h2>Revenue over time</h2><select aria-label="Chart type" value={chart} onChange={e=>C(e.target.value)}><option value="bar">Bars</option><option value="line">Line</option></select></div>{months.length?<><svg viewBox="0 0 600 200" role="img" aria-label="Monthly revenue chart">{[0,1,2,3].map(i=><line key={i} x1="10" x2="590" y1={20+i*50} y2={20+i*50} stroke="currentColor" opacity=".1"/>)}{chart==='line'&&<polyline fill="none" stroke="#5965ed" strokeWidth="4" points={months.map((m:any,i:number)=>(30+i*540/Math.max(1,months.length-1))+','+(175-m.revenue/max*145)).join(' ')}/>} {months.map((m:any,i:number)=>{const x=chart==='bar'?20+i*560/months.length:30+i*540/Math.max(1,months.length-1);return <g key={m.month}><title>{m.month}: {fmt(m.revenue)}</title>{chart==='bar'?<rect x={x} y={175-m.revenue/max*145} height={m.revenue/max*145} width={Math.max(2,560/months.length-8)} fill="#5965ed" rx="4"/>:<circle cx={x} cy={175-m.revenue/max*145} r="5" fill="#22a88a"/>}</g>;})}</svg><div className="scroll"><table><thead><tr><th>Month</th><th>Revenue</th></tr></thead><tbody>{months.map((m:any)=><tr key={m.month}><td>{m.month}</td><td>{fmt(m.revenue)}</td></tr>)}</tbody></table></div><small>Hover chart marks for values.</small></>:<p>No orders yet.</p>}</div>
 <div className="panel"><h2>Customer segments</h2><p>All data · as of {g?.as_of??'—'}</p><div className="donut" role="img" aria-label={counts.map(([k,n])=>k+': '+n).join(', ')} style={{background:total?'conic-gradient('+stops.join(',')+')':'#ddd'}}><div>{total}<small>customers</small></div></div>{counts.map(([k,n],i)=><p className="legend" key={k}><span style={{color:colors[i]}}>● {k}</span><b>{String(n)}</b></p>)}<small>At risk: recency &gt;60 days. Loyal: otherwise 4+ orders. Active: remaining.</small></div></section>
 <section className="panel"><div className="heading"><h2>Customer explorer</h2><button onClick={exportCSV}>Export filtered CSV</button></div><div className="toolbar"><input aria-label="Search customer" placeholder="Search customer ID" value={q} onChange={e=>{Q(e.target.value);P(1);}}/><select aria-label="Segment" value={segment} onChange={e=>{T(e.target.value);P(1);}}>{['All','Active','Loyal','At risk'].map(v=><option key={v}>{v}</option>)}</select><small>All data · sorted by spend</small></div><div className="scroll"><table><thead><tr>{['Customer','Recency days','Orders','Spend','Segment'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{customers.slice((page-1)*10,page*10).map((c:any)=><tr key={c.customer_id}><td>{c.customer_id}</td><td>{c.recency_days}</td><td>{c.frequency}</td><td>{fmt(c.monetary)}</td><td>{c.segment}</td></tr>)}</tbody></table></div>{!customers.length&&<p>No matching customers.</p>}<div className="toolbar"><button disabled={page<=1} onClick={()=>P(page-1)}>Previous</button><span>Page {page} / {Math.max(1,Math.ceil(customers.length/10))}</span><button disabled={page*10>=customers.length} onClick={()=>P(page+1)}>Next</button></div></section>
 <section className="panel"><div className="heading"><h2>Model comparison</h2><button disabled={busy} onClick={compare}>Compare models</button></div><p>All data · select by validation F1; evaluate on a separate later test period.</p>{r?.status==='ok'?<><p className="callout">Selected: <b>{r.selected}</b> · Validation {r.validation_cutoff} · Test {r.test_cutoff}</p><div className="scroll"><table><thead><tr><th>Candidate</th><th>Validation accuracy</th><th>Precision</th><th>Recall</th><th>F1</th></tr></thead><tbody>{r.models.map((m:any)=><tr key={m.name}><td>{m.name}</td>{['accuracy','precision','recall','f1'].map(k=><td key={k}>{(m.validation[k]*100).toFixed(1)}%</td>)}</tr>)}</tbody></table></div><p>Final test F1: {(r.test.f1*100).toFixed(1)}% · Test baseline F1: {(r.test_baseline.f1*100).toFixed(1)}%</p><p>Examples: {r.train_examples} train / {r.validation_examples} validation / {r.test_examples} test.</p><small>{r.note} Synthetic metrics do not establish real-world lift.</small></>:<p>{r?.message??'Upload multi-month history, then click Compare models. No model is deployed automatically.'}</p>}</section>
 <section className="panel"><h2>Recent uploads</h2><div className="scroll"><table><thead><tr>{['File','Time','Added','Updated','Unchanged'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{u.map(x=><tr key={x.id}><td>{x.filename}</td><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.added}</td><td>{x.updated}</td><td>{x.unchanged}</td></tr>)}</tbody></table></div></section><footer>Independent portfolio MVP · Uploads combine with stored orders · RFM is rule-based</footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
